# Generated by Django 3.1.1 on 2020-09-27 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('numero_guia', models.IntegerField(primary_key=True, serialize=False)),
                ('data_consulta', models.DateField()),
                ('valor_consulta', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='HashFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('codigo_medico', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exame', models.CharField(max_length=30)),
                ('valor_exame', models.FloatField()),
                ('numero_guia_consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relatorio.consulta')),
            ],
        ),
        migrations.AddField(
            model_name='consulta',
            name='codigo_medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relatorio.medico'),
        ),
    ]
